# .github/workflows/example-2.yml

name: Manual Inputs
on: 
  workflow_dispatch:

        
 name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
