# .github/workflows/example-2.yml

name: Manual Inputs
on: 
  workflow_dispatch:
jobs:
  my-job:
    name: Example JOb
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
